### PR TITLE
save and load the model

### PR DESCRIPTION
**Pull request by 1995parham**
I added a code for saving and loading the model by writing and reading it from files. I think it may be useful for others too so I created this PR.

### CODE REVIEW

**Comment by BaseMax** [comment]
It's a bit old repository and maybe archived, But I think @lucasromanosantos need to find a chance to look on this PR.

**Comment by 1995parham** [comment]
Thanks @BaseMax, I hope he can review my PR

**Comment by 1995parham** [comment]
Resolved in [cnn-c-cuda](https://github.com/1995parham/cnn-c-cuda).

**Comment by lucasromanosantos** [comment]
Hey @1995parham @BaseMax .

I'm so sorry I just noticed this today. Just got the email notification with the PR closed

I did this repo when I was in college long time ago. I haven't touched C and CUDA since then so I don't even think I would be able to review it  😅 

I'm happy that this repo may have been useful somehow to you and happy that you created your own.

Again, sorry for missing it. 

Let me know if I can assist with anything!

**Comment by 1995parham** [comment]
Hi @lucasromanosantos :wave: 

Thanks for your kind response. If you want I can re-open this PR also I can serve another copy of your repository on my account.

**Comment by lucasromanosantos** [comment]
I prefer if you continue the repo on your account. I'll be in much better hands 😸 

I'll put this one on read-only just in case.

@1995parham Thanks! I also love Golang btw

**Comment by 1995parham** [comment]
Thanks, @lucasromanosantos. Great to know you. If there is anything we can do together, I am in :see_no_evil:

**Comment by lucasromanosantos** [comment]
Same! Reach me if you think of anything!!

Nice meeting you as well

Cheers! :-)

**Pull request closed without merging**
